### ISSUE TITLE
USER STORY: Publish a poll

### ISSUE THREAD

**Issue by teresabowe** [teresabowe/agile-project-template#5]
In order to automatically hide the poll as an administrator, I can pick the expiry date while publishing the poll

## Acceptance Criteria:
* The poll should disappear at 11:59 on 11/11/2022
* A new poll message should display on the home page
* Expiry date for admin is added

## Tasks:

- [ ] Add date picker using HTML and CSS
- [ ] Create a job to check expired dates
- [ ] Test the functionality
